// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AgaintestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void againtest() {
    driver.Navigate().GoToUrl("https://practice.bpbonline.com/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1266, 816);
    driver.FindElement(By.CssSelector("#tdb3 > .ui-button-text")).Click();
    driver.FindElement(By.CssSelector("#tdb4 > .ui-button-text")).Click();
    driver.FindElement(By.Name("firstname")).Click();
    driver.FindElement(By.Name("gender")).Click();
    driver.FindElement(By.Name("firstname")).Click();
    driver.FindElement(By.Name("firstname")).SendKeys("frefrefer");
    driver.FindElement(By.Name("lastname")).Click();
    driver.FindElement(By.Name("lastname")).SendKeys("frefrefrefer");
    driver.FindElement(By.Id("dob")).Click();
    driver.FindElement(By.Id("dob")).SendKeys("12/25/1986");
    driver.FindElement(By.Id("dob")).SendKeys(Keys.Enter);
    driver.FindElement(By.Name("email_address")).Click();
    driver.FindElement(By.Name("email_address")).SendKeys("dzaxwfwe@gmail.com");
    driver.FindElement(By.Name("street_address")).Click();
    driver.FindElement(By.Name("street_address")).SendKeys("Varna");
    driver.FindElement(By.Name("postcode")).Click();
    driver.FindElement(By.Name("postcode")).SendKeys("9000");
    driver.FindElement(By.Name("city")).Click();
    driver.FindElement(By.Name("city")).SendKeys("Varna");
    driver.FindElement(By.Name("state")).Click();
    driver.FindElement(By.Name("state")).SendKeys("Vladislavovo");
    driver.FindElement(By.Name("country")).Click();
    {
      var dropdown = driver.FindElement(By.Name("country"));
      dropdown.FindElement(By.XPath("//option[. = 'Bulgaria']")).Click();
    }
    driver.FindElement(By.Name("telephone")).Click();
    driver.FindElement(By.Name("telephone")).SendKeys("0884003545");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("mitko123");
    driver.FindElement(By.Name("confirmation")).Click();
    driver.FindElement(By.Name("confirmation")).SendKeys("mitko123");
    driver.FindElement(By.CssSelector("#tdb4 > .ui-button-text")).Click();
    driver.FindElement(By.Id("bodyWrapper")).Click();
  }
}
