// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginformTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginform() {
    driver.Navigate().GoToUrl("https://practice.bpbonline.com/login.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1266, 816);
    driver.FindElement(By.CssSelector("#tdb4 > .ui-button-text")).Click();
    driver.FindElement(By.Name("gender")).Click();
    driver.FindElement(By.Name("firstname")).Click();
    driver.FindElement(By.Name("firstname")).SendKeys("Dimityr");
    driver.FindElement(By.Name("lastname")).Click();
    driver.FindElement(By.Name("lastname")).SendKeys("Dzhambazov");
    driver.FindElement(By.Id("dob")).Click();
    driver.FindElement(By.Id("dob")).SendKeys("12/25/1986");
    driver.FindElement(By.Id("dob")).SendKeys(Keys.Enter);
    driver.FindElement(By.Name("email_address")).Click();
    driver.FindElement(By.Name("email_address")).SendKeys("dzambazov1986@gmail.com");
    driver.FindElement(By.Name("email_address")).SendKeys(Keys.Enter);
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Errors have occured during the process of your form.\n\nPlease make the following corrections:\n\n* Your Street Address must contain a minimum of 5 characters.\n* Your Post Code must contain a minimum of 4 characters.\n* Your City must contain a minimum of 3 characters.\n* Your State must contain a minimum of 2 characters.\n* You must select a country from the Countries pull down menu.\n* Your Telephone Number must contain a minimum of 3 characters.\n* Your Password must contain a minimum of 5 characters.\n"));
    driver.FindElement(By.Name("street_address")).Click();
    driver.FindElement(By.Name("street_address")).SendKeys("Vladislavovo");
    driver.FindElement(By.CssSelector(".contentText:nth-child(6) tr:nth-child(2) > .fieldKey")).Click();
    driver.FindElement(By.Name("postcode")).Click();
    driver.FindElement(By.Name("postcode")).SendKeys("9000");
    driver.FindElement(By.Name("city")).Click();
    driver.FindElement(By.Name("city")).SendKeys("Varna");
    driver.FindElement(By.CssSelector("tr:nth-child(6) > .fieldKey")).Click();
    driver.FindElement(By.Name("state")).Click();
    driver.FindElement(By.Name("state")).SendKeys("Varna");
    driver.FindElement(By.Name("country")).Click();
    {
      var dropdown = driver.FindElement(By.Name("country"));
      dropdown.FindElement(By.XPath("//option[. = 'Bulgaria']")).Click();
    }
    driver.FindElement(By.Name("telephone")).Click();
    driver.FindElement(By.Name("telephone")).SendKeys("0884003545");
    driver.FindElement(By.CssSelector(".contentText:nth-child(8) tr:nth-child(3) > .fieldKey")).Click();
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("Mitko1986");
    driver.FindElement(By.Name("confirmation")).Click();
    driver.FindElement(By.CssSelector(".contentText:nth-child(10)")).Click();
    driver.FindElement(By.Name("password")).SendKeys("123456");
    driver.FindElement(By.Name("confirmation")).Click();
    driver.FindElement(By.Name("confirmation")).SendKeys("123456");
    driver.FindElement(By.CssSelector("#tdb4 > .ui-button-text")).Click();
    driver.FindElement(By.CssSelector(".grid_24:nth-child(7)")).Click();
  }
}
